### ISSUE TITLE
Badges View Error

### ISSUE THREAD

**Issue by ebollens** [universityofcalifornia/NeXt#201]
```
ActionView::Template::Error (undefined method `badge_roles' for #<User:0x007f66e89e3620>):
    10:   <% @badges.each do |badge| %>
    11:     <li>
    12:       <%= render badge.becomes(Badge) %>
    13:       <% if badge.is_editable_by? current_user %>
    14:         <%= button_to 'Edit',
    15:                       edit_badge_url(badge),
    16:                       method: :get,
  app/models/badge.rb:71:in `is_owned_by?'
  app/models/badge.rb:78:in `is_editable_by?'
  app/views/badges/index.html.erb:13:in `block in _app_views_badges_index_html_erb__2969242130055368611_39386140'
  app/views/badges/index.html.erb:10:in `_app_views_badges_index_html_erb__2969242130055368611_39386140'
```

**Comment by ctrance** [comment]
@krozett - Please add instructions on how to test this.

**Comment by krozett** [comment]
@ctrance This error was popping up whenever a non-admin user visited the badges page. You can test by going to https://ucnext.org/badges as a non-admin user, or not logged in. (There is an issue to add a link to that page somewhere, I believe.)

**Comment by ctrance** [comment]
@krozett - I don't see error viewing the badges as non-admin/not logged in user. I'm closing this...
